# -*- coding: utf-8 -*-
"""
v2.5A2 Raw spatial-organization attenuation analysis.

This script reads spatial_shuffle_timeseries.csv generated by v2.5A
and directly compares original vs spatial-shuffled raw spatial indicators.

Why:
    First-rise alarm time is not suitable for spatial-shuffle control because
    random shuffling may create artificial fragmentation and high gradients.

Main question:
    Are spatial organization indicators, such as Moran's I, local neighbor
    correlation, and sync edge ratio, reduced after spatial shuffling?
"""

from pathlib import Path

import numpy as np
import pandas as pd


RUNS = [
    (
        "vegetation",
        42,
        "0p50",
        Path("results/v2_5_controls/spatial_shuffle/vegetation_seed42_thr0p50"),
    ),
    (
        "vegetation",
        123,
        "0p50",
        Path("results/v2_5_controls/spatial_shuffle/vegetation_seed123_thr0p50"),
    ),
    (
        "seir",
        2026,
        "0p20",
        Path("results/v2_5_controls/spatial_shuffle/seir_seed2026_thr0p20"),
    ),
]


INDICATORS = [
    # Core spatial organization indicators
    "prepatch_moran_i",
    "prepatch_local_neighbor_corr_mean",
    "prepatch_sync_edge_ratio",

    # Gradient indicator: may increase after shuffle, so interpret separately
    "prepatch_gradient_top10_mean",

    # Control composite index from v2.5A
    "pwsi_control",

    # Patch and boundary indicators
    "edge_density",
    "patch_count",
    "largest_patch_ratio",
    "visible_patch_metric",

    # Dynamic indicators
    "PSII",
    "DPCI",
    "FPV",
    "PDSI",
]


WINDOWS = [
    ("baseline_window", -80, -50),
    ("early_precursor_window", -60, -30),
    ("late_precursor_window", -30, -1),
    ("full_precursor_window", -60, -1),
]


def cohen_d_paired(diff):
    diff = np.asarray(diff, dtype=float)
    diff = diff[np.isfinite(diff)]

    if len(diff) < 2:
        return np.nan

    sd = np.std(diff, ddof=1)

    if sd < 1e-12:
        return np.nan

    return float(np.mean(diff) / sd)


def summarize_one_run(system, seed, threshold, d):
    ts_path = d / "spatial_shuffle_timeseries.csv"

    if not ts_path.exists():
        print(f"Skip missing: {ts_path}")
        return None

    df = pd.read_csv(ts_path)

    out_rows = []

    for window_name, start, end in WINDOWS:
        w = df[
            (df["relative_time"] >= start)
            & (df["relative_time"] <= end)
        ].copy()

        if w.empty:
            continue

        original = w[
            (w["variant"] == "original")
            & (w["shuffle_run"] == 0)
        ].copy()

        shuffle = w[w["variant"] == "spatial_shuffle"].copy()

        if original.empty or shuffle.empty:
            continue

        for indicator in INDICATORS:
            if indicator not in w.columns:
                continue

            orig_sim = (
                original.groupby("sim_id")[indicator]
                .mean()
                .rename("original_mean")
                .reset_index()
            )

            shuf_sim = (
                shuffle.groupby(["sim_id", "shuffle_run"])[indicator]
                .mean()
                .reset_index()
                .groupby("sim_id")[indicator]
                .mean()
                .rename("shuffle_mean")
                .reset_index()
            )

            merged = orig_sim.merge(shuf_sim, on="sim_id", how="inner")
            merged = merged.replace([np.inf, -np.inf], np.nan).dropna()

            if merged.empty:
                continue

            diff = merged["original_mean"].to_numpy() - merged["shuffle_mean"].to_numpy()

            original_mean = float(merged["original_mean"].mean())
            shuffle_mean = float(merged["shuffle_mean"].mean())
            difference = float(np.mean(diff))

            if abs(original_mean) > 1e-12:
                relative_change = float((original_mean - shuffle_mean) / abs(original_mean))
            else:
                relative_change = np.nan

            # For core organization indicators, positive difference means
            # original spatial organization is stronger than shuffle.
            expected_original_greater = indicator in [
                "prepatch_moran_i",
                "prepatch_local_neighbor_corr_mean",
                "prepatch_sync_edge_ratio",
                "pwsi_control",
            ]

            # For gradient and edge/patch fragmentation indicators, shuffle may
            # be greater because random permutation creates noisy boundaries.
            if expected_original_greater:
                pass_flag = difference > 0
            else:
                pass_flag = np.nan

            out_rows.append({
                "system": system,
                "seed": seed,
                "threshold": threshold,
                "window": window_name,
                "indicator": indicator,
                "n_sims": int(len(merged)),
                "original_mean": original_mean,
                "shuffle_mean": shuffle_mean,
                "original_minus_shuffle": difference,
                "relative_change_vs_original": relative_change,
                "paired_cohen_d": cohen_d_paired(diff),
                "expected_original_greater": expected_original_greater,
                "pass_spatial_attenuation": pass_flag,
            })

    return pd.DataFrame(out_rows)


def main():
    all_rows = []

    for system, seed, threshold, d in RUNS:
        result = summarize_one_run(system, seed, threshold, d)

        if result is not None and not result.empty:
            all_rows.append(result)

    if not all_rows:
        raise SystemExit("No valid spatial-shuffle timeseries files found.")

    df = pd.concat(all_rows, ignore_index=True)

    outdir = Path("results/v2_5_controls/spatial_shuffle_raw_effects")
    outdir.mkdir(parents=True, exist_ok=True)

    df.to_csv(
        outdir / "raw_spatial_organization_shuffle_effects.csv",
        index=False,
        encoding="utf-8-sig",
    )

    core = df[
        df["indicator"].isin([
            "prepatch_moran_i",
            "prepatch_local_neighbor_corr_mean",
            "prepatch_sync_edge_ratio",
            "pwsi_control",
        ])
    ].copy()

    core.to_csv(
        outdir / "core_spatial_organization_shuffle_effects.csv",
        index=False,
        encoding="utf-8-sig",
    )

    print("\n=== Core spatial-organization attenuation effects ===")
    cols = [
        "system",
        "seed",
        "threshold",
        "window",
        "indicator",
        "n_sims",
        "original_mean",
        "shuffle_mean",
        "original_minus_shuffle",
        "relative_change_vs_original",
        "paired_cohen_d",
        "pass_spatial_attenuation",
    ]
    print(core[cols].to_string(index=False))

    print("\n=== Mean core effects by system, window and indicator ===")
    print(
        core.groupby(["system", "window", "indicator"])[
            ["original_minus_shuffle", "relative_change_vs_original", "paired_cohen_d"]
        ].mean().reset_index().to_string(index=False)
    )

    print("\n=== Pass rate for spatial attenuation ===")
    print(
        core.groupby(["system", "window"])["pass_spatial_attenuation"]
        .mean()
        .reset_index()
        .to_string(index=False)
    )


if __name__ == "__main__":
    main()
